class UserNotFoundError(Exception):
    pass 

class NoteNotFoundError(Exception):
    pass